# Generated by Django 2.0.dev20170731193407 on 2017-08-07 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20170807_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedetail',
            name='build',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='projects.Build'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issuedetail',
            name='issue',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='projects.Issue'),
            preserve_default=False,
        ),
    ]
