# Generated by Django 2.0.dev20170731193407 on 2017-08-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testscenariodetail',
            name='requisite',
            field=models.CharField(choices=[('REQUIRED', 'Yes'), ('REMOVED', 'Removed')], default='REQUIRED', max_length=10),
        ),
    ]
